# 
# Vagrantfile per i progetti client-server 
# - un nodo server Oracle Java SDK 8, Maven, wildfly 10
# - un nodo client Oracle Java SDK 8, Maven, wildfly 10
# 

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Configurazioni comuni.

    # Ubuntu 16.04 LTS 64 bit VirtualBox (Bento)
	config.vm.box = "bento/ubuntu-16.04"
	#config.vm.box = "debian/jessie64"
    # config.vm.box_url = "https://app.vagrantup.com/bento/boxes/ubuntu-16.04"

    # folder per i progetti Asw (/home/asw/projects)
    config.vm.synced_folder "../../projects/", "/home/asw/projects", :mount_options => ["dmode=777", "fmode=777"]

    # folder per le risorse condivise per gli ambienti Asw (/home/asw/_shared/resources e /home/asw/_shared/scripts) 
    config.vm.synced_folder "../_shared/", "/home/asw/_shared", :mount_options => ["dmode=777", "fmode=777"]

    #
    # Configurazione del nodo "server", che prevede: 
    # - Oracle Java SDK 8 
    # - Maven
	# - wildfly 10
    config.vm.define "server" do |node|
        node.vm.hostname = "server"    
        node.vm.network "private_network", ip: "10.11.1.101", virtualbox__intnet: true

        node.vm.provider "virtualbox" do |v| 
            v.memory = 1024 
			v.cpus = 1
        end 

        node.vm.network "forwarded_port", guest: 22, host: 2211, id: 'ssh', auto_correct: true
        node.ssh.forward_agent = true

        # node.vm.network "forwarded_port", guest: 8080, host: 8080
 
        # provisioning con bash 
        node.vm.provision :shell, :inline => 'apt-get update'
        node.vm.provision :shell, path: "../_shared/scripts/setup-java.sh"
        node.vm.provision :shell, :inline => "echo '10.11.1.101 server' >> /etc/hosts"
        node.vm.provision :shell, :inline => "echo '10.11.1.201 client' >> /etc/hosts"
  		node.vm.provision :shell, path: "../_shared/scripts/setup-wildfly.sh"
		node.vm.provision :shell, path: "../_shared/scripts/setup-maven.sh"	
		node.vm.provision :shell, path: "../_shared/scripts/add-usersSL.sh"	#SL use this sh on server, vagrant ssh server 
		node.vm.provision :shell, path: "../_shared/scripts/startup-wildfly.sh" #SL use this sh on server, vagrant ssh server	
		
		# crea un link simbolico alla cartella dei progetti asw nella cartella dell'utente di default 
        node.vm.provision :shell, :inline => 'ln -s /home/asw/projects projects'
		

        node.vm.provision :shell, 
            inline: "echo  'configurazione nodo server completata'"

    end

    #
    # Configurazione del nodo "client", che prevede: 
    # - Oracle Java SDK 8
    # - Maven 
    config.vm.define "client" do |node|
        node.vm.hostname = "client"    
        node.vm.network "private_network", ip: "10.11.1.201", virtualbox__intnet: true

        node.vm.provider "virtualbox" do |v| 
            v.memory = 1024 
			v.cpus = 1
        end 

        node.vm.network "forwarded_port", guest: 22, host: 2221, id: 'ssh', auto_correct: true
        node.ssh.forward_agent = true
 
        # provisioning con bash 
        node.vm.provision :shell, :inline => 'apt-get update'
        node.vm.provision :shell, path: "../_shared/scripts/setup-java.sh"
        node.vm.provision :shell, :inline => "echo '10.11.1.101 server' >> /etc/hosts"
        node.vm.provision :shell, :inline => "echo '10.11.1.201 client' >> /etc/hosts"
		node.vm.provision :shell, path: "../_shared/scripts/setup-wildfly.sh"
		node.vm.provision :shell, path: "../_shared/scripts/setup-maven.sh"	
		node.vm.provision :shell, path: "../_shared/scripts/deploy-ejb-remoteSL.sh"	#SL use this sh on client, vagrant ssh client it deploy the ejb on the server and run the appclient.sh to call the server
		
		# crea un link simbolico alla cartella dei progetti asw nella cartella dell'utente di default 
        node.vm.provision :shell, :inline => 'ln -s /home/asw/projects projects'
		
		#node.vm.provision :shell, path: "../_shared/scripts/run-appSL.sh"	


        node.vm.provision :shell, 
            inline: "echo  'configurazione nodo client completata'"

    end

end
